fwitter/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  root 'homes#top'
  resources :posts do
 	resource :post_comments, only: [:create, :destroy]
 	resource :likes, only: [:create, :destroy]
 end
  resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

fwitter/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

fwitter/app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

fwitter/app/models/post.rb
class Post < ApplicationRecord
	validates :body, {presence:true, length: {maximum: 120}}
	attachment :image
	belongs_to :user,optional: true
	has_many :post_comments, dependent: :destroy
	has_many :likes, dependent: :destroy
	def liked_by?(user)
		likes.where(user_id: user.id).exists?
	end
end

fwitter/app/models/post_comment.rb
class PostComment < ApplicationRecord
	validates :comment, {presence:true, length: {maximum: 120}}
	belongs_to :user
	belongs_to :post
end

fwitter/app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
   validates :follower_id, presence: true
  validates :followed_id, presence: true
end

fwitter/app/models/user.rb
class User < ApplicationRecord
	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	validates :name, {presence:true, length: {maximum: 10}, on: :update}
	validates :introduction, {presence:true, length: {maximum: 120}, on: :update}
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  attachment :profile_image

  has_many :active_relationships, class_name:  "Relationship",foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name:  "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  # ユーザーをフォローする
  def follow(other_user)
    following << other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

end

fwitter/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters,if: :devise_controller?
	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
	end
	def after_sign_in_path_for(resource)
      if current_user
        posts_path
      end
    end
    def after_sign_out_path_for(resource)
    	root_path
  end
end

fwitter/app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def top
	end
end

fwitter/app/controllers/likes_controller.rb
class LikesController < ApplicationController
	def create
		post = Post.find(params[:post_id])
		like = current_user.likes.new(post_id: post.id)
		like.save
		redirect_to post_path(post)
	end
	def destroy
		post = Post.find(params[:post_id])
		like = current_user.likes.find_by(post_id: post.id)
		like.destroy
		redirect_to post_path(post)
	end
end

fwitter/app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
	def create
		post = Post.find(params[:post_id])
		comment = PostComment.new(post_comment_params)
		comment.user_id = current_user.id
		comment.post_id = post.id
		comment.save
		redirect_to post_path(post)
	end
	private
	def post_comment_params
		params.require(:post_comment).permit(:comment)
	end
end

fwitter/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user,{only: [:edit,:update,:destroy]}
  def new
  	@post = Post.new
  end
  def create
  	@post = Post.new(post_params)
    @post.user_id = current_user.id
  	if @post.save
  	redirect_to post_path(@post)
  else
  	render :new
  end
  end
  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
    @like = Like.new
     @users = User.page(params[:page]).reverse_order
  end
  def index
  	@posts = Post.all
    @post_comment = PostComment.new
    @like = Like.new
     @users = User.page(params[:page]).reverse_order
  end

  def edit
  	@post = Post.find(params[:id])
  end
  def update
  	@post = Post.find(params[:id])
  	if @post.update(post_params)
  		redirect_to post_path(@post)
  	else
  		render :edit
  	end
  end
  def destroy
  	@post = Post.find(params[:id])
  	@post.destroy
  	redirect_to posts_path
  end

  private
  def ensure_correct_user
    @post = Post.find(params[:id])
    if @post.user_id != current_user.id
    redirect_to posts_path
    end
  end
  def post_params
  	params.require(:post).permit(:body, :image, :user_id)
  end
end

fwitter/app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	before_action :authenticate_user!
  def create
    user = User.find(params[:followed_id])
    current_user.follow(user)
    redirect_to users_path
  end

  def destroy
    user = Relationship.find(params[:id]).followed
    current_user.unfollow(user)
    redirect_to users_path
  end

end

fwitter/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, {only: [:edit,:update,:destroy]}
  def show
  	@user = User.find(params[:id])
  	@posts = @user.posts.page(params[:page]).reverse_order
    @users = User.page(params[:page]).reverse_order
  end

  def index
  	@user = User.all
    @users = User.page(params[:page]).reverse_order
  end

  def edit
  	@user = User.find(params[:id])
  end
  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  	redirect_to user_path(@user)
  else
    render :edit
  end
  end
  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.page(params[:page]).reverse_order
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.page(params[:page]).reverse_order
    render 'show_follow'
  end

  private
   def ensure_correct_user
    @user = User.find(params[:id])
    if current_user != @user
    redirect_to user_path(current_user.id)
  end
  end
  def user_params
  	params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

fwitter/app/helpers/application_helper.rb
module ApplicationHelper
end

fwitter/app/helpers/homes_helper.rb
module HomesHelper
end

fwitter/app/helpers/likes_helper.rb
module LikesHelper
end

fwitter/app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

fwitter/app/helpers/posts_helper.rb
module PostsHelper
end

fwitter/app/helpers/relationships_helper.rb
module RelationshipsHelper
end

fwitter/app/helpers/users_helper.rb
module UsersHelper
end

fwitter/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fwitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://kit.fontawesome.com/f3fffa880e.js" crossorigin="anonymous' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% if flash[:notice] %>
    <div class="flash">
    <%= flash[:notice]%>
    </div>
      <% end %>
    <%= yield %>
  </body>
</html>

fwitter/app/views/posts/_aside.html.erb
<aside class="aside mobile_non">
			<form class="form">
					<input type="search" name="" value="" placeholder="キーワード検索" class="search_form">
					<%= fa_icon 'search', class:"search_icon" %>
				</form>
		<div class="aside_cont pink_bg">
			<h3 class="txts txtbold">Japan trends</h3>
				<div class="box trend_info">
							<p class="txtxs gray">日本トレンド</p>
							<p class="txts">予言通り</p>
							<p class="txts gray">3,567件のフイート</p>
					</div>
					<div class="box trend_info">
							<p class="txtxs gray">日本トレンド</p>
							<p class="txts">予言通り</p>
							<p class="txts gray">3,567件のフイート</p>
					</div>
					<div class="box trend_info">
							<p class="txtxs gray">日本トレンド</p>
							<p class="txts">予言通り</p>
							<p class="txts gray">3,567件のフイート</p>
					</div>
					<h3 class="showmore"><%= link_to posts_path, class:"txts pink" do %>
						Show more
						<% end %></h3>
		</div>
		<div class="aside_cont pink_bg">
			<h3 class="txts txtbold">Who to follow</h3>
			<% @users.each do |user| %>
					<div class="box users">
					<%= link_to user_path(user) do %>
					<div class="user_cont">
						<div class="user_icon">
							<%= attachment_image_tag user, :profile_image, :fill,1000,1000, fallback:"logo.png",  class:"user_img"%>
						</div>
						<div class="user_name black">
							<p class="txts txtbold"><%= user.name %></p><p class="txts gray">@<%= user.id %></p><br>
						</div>
					</div>
					<a href="" class="user_btn">
						<div class="btns btnwhite">Follow</div>
					</a>
				<% end %>
					</div>
				<% end %>
					<h3 class="showmore">
						<%= link_to users_path, class:"txts pink" do %>
						Show more
						<% end %>
					</h3>
		</div>
	<footer class="footer">
			<p class="txtxs">利用規約　プライバシーポリシー　Cookie　広告情報<br>もっと見る　©︎2020 Fwitter, Inc.</p>
		</footer>
	</aside>
</div>

fwitter/app/views/posts/_error.html.erb
 <% if post.errors.any? %>
  <div id="error_explanation" class="error_messages">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: post.errors.count,
                 resource: post.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% post.errors.full_messages.each do |message| %>
        <li class="error_messages_list"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

fwitter/app/views/posts/_header.html.erb
<div class="wrap mobile_flex">
<header class="header">
		<nav class="nav mobile_fixed_left">
			<ul class="list">
				<li class="nav_cont">
					<%= link_to root_path do %>
						<img src="/assets/logo.png" class="logo">
					<% end %>
					</a>
				</li>

				<li class="nav_cont">
					<%= link_to(posts_path, class:"txtl txtbold") do %>
						<%= fa_icon 'home', class:"fa-fw"%>Home
					<% end %>
					</li>
				<li class="nav_cont">
					<%= link_to(users_path, class:"txtl txtbold") do %>
					<%= fa_icon 'user', class:"fa-fw" %>Users
					<% end %>
				</li>
				<li class="nav_cont"><a href="" title="" class="txtl txtbold"><%= fa_icon 'bell', class:"fa-fw" %>Alert</a></li>
				<li class="nav_cont"><a href="" title="" class="txtl txtbold"><%= fa_icon 'envelope', class:"fa-fw" %>Messages</a></li>
				<li class="nav_cont"><a href="" title="" class="txtl txtbold"><%= fa_icon'bookmark', class:"fa-fw"%>Bookmarks</a></li>
				<li class="nav_cont"><a href="" title="" class="txtl txtbold"><%= fa_icon'list-alt', class:"fa-fw"%>Lists</a></li>
				<li class="nav_cont">
					<%= link_to(user_path(current_user), class:"txtl txtbold") do %>
					<%= fa_icon'id-card', class:"fa-fw"%>Profile
					<% end %>
				</li>
				<li class="nav_cont"><a href="" title="" class="txtl txtbold"><%= fa_icon'chevron-circle-down', class:"fa-fw"%>More</a></li>
			</ul>
			<ul class="mobile_list">
				<li class="nav_cont">
					<%= link_to root_path do %>
						<img src="/assets/logo.png" class="logo">
					<% end %>
					</a>
				</li>

				<li class="nav_cont">
					<%= link_to(posts_path, class:"txtl txtbold") do %>
						<%= fa_icon 'home', class:"fa-fw"%>
					<% end %>
					</li>
				<li class="nav_cont">
					<%= link_to(users_path, class:"txtl txtbold") do %>
					<%= fa_icon 'user', class:"fa-fw" %>
					<% end %>
				</li>
				<li class="nav_cont"><a href="" title="" class="txtl txtbold"><%= fa_icon 'bell', class:"fa-fw" %></a></li>
				<li class="nav_cont"><a href="" title="" class="txtl txtbold"><%= fa_icon 'envelope', class:"fa-fw" %></a></li>
				<li class="nav_cont"><a href="" title="" class="txtl txtbold"><%= fa_icon'bookmark', class:"fa-fw"%></a></li>
				<li class="nav_cont"><a href="" title="" class="txtl txtbold"><%= fa_icon'list-alt', class:"fa-fw"%></a></li>
				<li class="nav_cont">
					<%= link_to(user_path(current_user), class:"txtl txtbold") do %>
					<%= fa_icon'id-card', class:"fa-fw"%>
					<% end %>
				</li>
				<li class="nav_cont"><a href="" title="" class="txtl txtbold"><%= fa_icon'chevron-circle-down', class:"fa-fw"%></a></li>
			</ul>
			<%= link_to(new_post_path, class:"fweet_btn") do%>
						<div class="btnm btnpink">Fweet</div>
					<% end %>
			<div class="users">
				<%= link_to(user_path(current_user), class:"profile_icon") do %>
						<div class="user_cont">
							<div class="user_icon">
								<%= attachment_image_tag current_user, :profile_image, :fill,1000,1000, fallback:"logo.png",  class:"user_img"%>
							</div>
							<div class="user_name">
									<p class="txts txtbold black"><%= current_user.name %></p>
									<p class="txts gray">@<%= current_user.id %></p>
							</div>
							</div>
					<% end %>
			</div>
		</nav>
	</header><!-- /header -->

fwitter/app/views/posts/edit.html.erb
<%= render "posts/error", post:@post %>
<div class="form_wrap pink_border">
		<h2 class="txtl">Fweet</h2>
		<div class="fweet_form">
		<%= form_for(@post) do |f| %>
			<%= f.text_area :body, class:"form_txtarea"%>
			<%= f.attachment_field :image%>
			<div class="align-right">
				<%= f.submit "Fweet", class:"btns btnpink txts fweet_btn" %>
			</div>
		<% end %>
		</div>
	</div>

fwitter/app/views/posts/index.html.erb
<%= render 'posts/header', user:@user %>

<main class="main">

		<h2 class="txtm txtbold mobile_fixed_head">Home</h2>
		<div class="mobile_head"></div>
			<% @posts.each do |post| %>
			<%= link_to post_path(post.id) do %>
			<div class="box posts">
					<div class="user_icon">
						<%= attachment_image_tag post.user, :profile_image, :fill,1000,1000, fallback:"logo.png",  class:"user_img"%>
					</div>
					<div class="user_name">
						<p class="txts txtbold black"><%= post.user.name %></p>
						<p class="txts gray">@<%= post.user.id %></p>
						<p class="txts body_txt black"><%= post.body %></p>
						 <%= attachment_image_tag post, :image, class:"post_img"%>
						<div class="index_post_info">
							<a href="" class="txtxs gray comments">
								<%= fa_icon 'comment', class:"fa-fw" %><%= post.post_comments.count %>
							</a>
							<% if post.liked_by?(current_user) %>
	    						<%= link_to post_likes_path(post.id), method: :delete, class:"txtxs gray likes" do %>
	    							<%= fa_icon 'heart', class:"fa-fw", style:"color: #f21d99;" %><%= post.likes.count %>
	    						<% end %>
							<% else %>
	    						<%= link_to post_likes_path(post.id), method: :post, class:"txtxs gray likes" do %>
	    							<%= fa_icon 'heart', class:"fa-fw" %><%= post.likes.count %>
	    						<% end %>
							<% end %>
						</div>
					</div>
				<% end %>
			</div>
			<% end %>
	</main>

<%= render 'posts/aside', user:@user %>

fwitter/app/views/posts/new.html.erb
<%= render "posts/error", post:@post %>
<div class="form_wrap pink_border">
		<h2 class="txtl">Fweet</h2>
		<div class="fweet_form">
		<%= form_for(@post) do |f| %>
			<%= f.text_area :body, class:"form_txtarea"%>
			<%= f.attachment_field :image%>
			<div class="align-right">
				<%= f.submit "Fweet", class:"btns btnpink txts fweet_btn" %>
			</div>
		<% end %>
		</div>
	</div>

fwitter/app/views/posts/show.html.erb
<%= render 'posts/header', user:@user %>

<main class="main">

		<h2 class="txtm txtbold mobile_fixed_head">Home</h2>
		<div class="mobile_head"></div>
		<%= link_to user_path(@post.user) do %>
			<div class="box posts black">
					<div class="user_icon">
						<%= attachment_image_tag @post.user, :profile_image, :fill,1000,1000, fallback:"logo.png",  class:"user_img"%>
					</div>
					<div class="user_name">
						<p class="txts txtbold"><%= @post.user.name %></p>
						<p class="txts gray">@<%= @post.user.id %></p>
						<p class="txts body_txt"><%= @post.body %></p>
						 <%= attachment_image_tag @post, :image, class:"post_img"%>
					</div>
			</div>
			<% end %>
			<div class="box post_info">
							<a href="" class="txtxs gray comments"><%= fa_icon 'comment', class:"fa-fw" %><%= @post.post_comments.count %></a>
							<% if @post.liked_by?(current_user) %>
	    						<%= link_to post_likes_path(@post.id), method: :delete, class:"txtxs gray likes" do %>
	    						<%= fa_icon 'heart', class:"fa-fw", style:"color: #f21d99;" %><%= @post.likes.count %>
	    						<% end %>
							<% else %>
	    						<%= link_to post_likes_path(@post.id), method: :post, class:"txtxs gray likes" do %>
	    						<%= fa_icon 'heart', class:"fa-fw" %><%= @post.likes.count %>
	    						<% end %>
						<% end %>
							<% if @post.user == current_user %>
							<%= link_to "編集", edit_post_path(@post.id), class:"txtxs gray destroy" %>
							<%= link_to "削除", post_path(@post.id), method: :delete, class:"txtxs gray destroy" %>
							<% end %>
			</div>
			<div class="box space txts txtbold pink pink_bg">comments</div>
			<% @post.post_comments.each do |post_comment| %>
			<div class="comment_box posts">
					<div class="user_icon">
						<img src="/assets/logo.png" class="user_img">
					</div>
					<div class="user_name">
						<p class="txts txtbold"><%= post_comment.user.name %></p>
						<p class="txts gray">@<%= post_comment.user.id %></p>
						<p class="txts body_txt"><%= post_comment.comment %></p>
					</div>
				</div>
				<% end %>
			<%= render "posts/error", post:@post %>
				<div class="comment_form">
				<h2 class="txtl">Comment</h2>
				<div class="fweet_form">
			<%= form_for [@post, @post_comment] do |f| %>
				<%= f.text_area :comment, class:"form_txtarea"%>
				<div class="align-right">
				<%= f.submit "Save", class:"btns btnpink txts save_btn" %>
				</div>
				<% end %>
			</div>
	</div>
	</main>

<%= render 'posts/aside' , user:@user %>