sample_app/config/routes.rb
Rails.application.routes.draw do
  get 'todolists/new'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'top' => 'homes#top'

  post 'todolists' => 'todolists#create'
  get 'todolists' => 'todolists#index'
  get 'todolists/:id' => 'todolists#show', as:'todolist'
  get 'todolists/:id/edit' => 'todolists#edit', as:'edit_todolist'
  patch 'todolists/:id' => 'todolists#update', as: 'update_todolist'
  delete 'todolists/:id' => 'todolists#destroy', as: 'destroy_todolist'
end

sample_app/app/models/li.rb
class Li < ApplicationRecord
end

sample_app/app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def top

	end

end

sample_app/app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
  def new
  	# Viewへ渡すためのインスタンス変数に空のモデルオブジェクトを生成する。
  	 @list = List.new
  end

  def create
        # ストロングパラメーターを使用
         list = List.new(list_params)
        # DBへ保存する
         list.save
        # トップ画面へリダイレクト
        redirect_to todolist_path(list.id)
    end
    def index
      @lists = List.all
    end
    def show
      @list =  List.find(params[:id])
    end
    def edit
      @list = List.find(params[:id])
    end
    def update
      list = List.find(params[:id])
        list.update(list_params)
        redirect_to todolist_path(list.id)
    end
    def destroy
      list = List.find(params[:id]) #データ(レコード)を1件取得
        list.destroy #データ（レコード）を削除
        redirect_to todolists_path #List一覧画面へリダイレクト
    end
    private

    def list_params
        params.require(:list).permit(:title, :body, :image)
    end
end

sample_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <link href="https://fonts.googleapis.com/css?family=Kaushan+Script rel="stylesheet">
  </head>

  <body>
     <header>
      <h1 class="headline"> All Lists </h1>
    </header>
    <nav>
      <ul class="nav-list">
        <li class="nav-list-item">
          <%= link_to "Top", top_path %>
        </li>
        <li class="nav-list-item">
          <%= link_to "TodoLists", todolists_path %>
        </li>
        <li class="nav-list-item">
          <%= link_to "New List", todolists_new_path %>
        </li>
      </ul>
    </nav>
  <main>
    <%= yield %>
    </main>
  </body>
</html>

sample_app/app/views/todolists/edit.html.erb
<h1>編集画面</h1>
<%= form_for(@list, url:"/todolists/#{@list.id}") do |f| %>
    <h4>タイトル</h4>
    <%= f.text_field :title %>
    <h4>本文</h4>
    <%= f.text_area :body %>
    <%= f.submit '保存' %>
<% end %>

sample_app/app/views/todolists/index.html.erb
<% @lists.each do |list| %>
  <div class="list-box">
    <%= attachment_image_tag list, :image, :fill, 200, 200, format: 'jpeg' %>
    <div class="list-comment">
      <span class="list-body"><%= list.body %></span>
      <span class="list-title"><%=link_to list.title, todolist_path(list.id) %></span>
    </div>
  </div>
  <% end %>

sample_app/app/views/todolists/new.html.erb
<h1>新規投稿</h1>
<!--form_for部分-->
<%= form_for(@list, url:'/todolists') do |f| %>

	<h4>タイトル</h4>
	<%= f.text_field :title %>

	<h4>本文</h4>
	<%= f.text_area :body %>
	<!-- 追加部分 -->
  <h4>画像</h4>
  <%= f.attachment_field :image %>

	<%= f.submit '投稿' %>

<% end %>