meshiterro2/config/routes.rb
Rails.application.routes.draw do
root 'post_images#index'
  devise_for :users
  resources :post_images, only: [:new, :create, :index, :show, :destroy] do
  	resource :favorites, only: [:create, :destroy]
  	resource :post_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

meshiterro2/app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :post_image
end

meshiterro2/app/models/post_comment.rb
class PostComment < ApplicationRecord
	belongs_to :user
	belongs_to :post_image
end

meshiterro2/app/models/post_image.rb
class PostImage < ApplicationRecord
	belongs_to :user
	attachment :image
	has_many :post_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	validates :shop_name, presence: true
    validates :image, presence: true
	def  favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
end

meshiterro2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :post_images, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image
end

meshiterro2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
	before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

meshiterro2/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def create
	post_image = PostImage.find(params[:post_image_id])
	favorite = current_user.favorites.new(post_image_id: post_image.id)
	favorite.save
	redirect_to post_image_path(post_image)
	end
	def destroy
		post_image = PostImage.find(params[:post_image_id])
		favorite = current_user.favorites.find_by(post_image_id: post_image.id)
		favorite.destroy
		redirect_to post_image_path(post_image)
	end
end

meshiterro2/app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
	def create
		post_image = PostImage.find(params[:post_image_id])
		comment = current_user.post_comments.new(post_comment_params)
		comment.post_image_id = post_image.id
		comment.save
		redirect_to post_image_path(post_image)
	end
	private
	def post_comment_params
		params.require(:post_comment).permit(:comment)
	end
end

meshiterro2/app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
	def new
		@post_image = PostImage.new
    end
    def create
    	@post_image = PostImage.new(post_image_params)
    	@post_image.user_id =current_user.id
    	if @post_image.save
    	   redirect_to post_images_path
        else
            render :new
        end
    end
    def index
    	@post_images = PostImage.page(params[:page]).reverse_order
    end
    def show
    	@post_image = PostImage.find(params[:id])
        @post_comment = PostComment.new
    end
    def destroy
        @post_image = PostImage.find(params[:id])
        @post_image.destroy
        redirect_to post_images_path
    end
    private
    def post_image_params
    	params.require(:post_image).permit(:shop_name, :image, :caption)
    end
end

meshiterro2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  	@post_images = @user.post_images.page(params[:page]).reverse_order
  end
  def edit
  	@user = User.find(params[:id])
  end
  def update
  	@user = User.find(params[:id])
  	@user.update(user_params)
  	redirect_to user_path(@user.id)
  end
  private
  def user_params
  	params.require(:user).permit(:name, :profile_image)
  end
end

meshiterro2/app/helpers/favorites_helper.rb
module FavoritesHelper
end

meshiterro2/app/helpers/post_images_helper.rb
module PostImagesHelper
end

meshiterro2/app/views/post_images/index.html.erb
<section class="sct-color-1 slice">
  <div class="container-fluid masonry-container">
    <div class="row">
      <div class="col-md-8 col-sm-offset-2">
        <div class="masonry-wrapper-cols">
          <div class="masonry-gutter"></div>
            <% @post_images.each do |post_image| %>
            <div class="masonry-block">
              <div class="block block-image v1">
                <div class="block-image">
                  <div class="view view-first">
                    <%= link_to post_image_path(post_image.id) do %>
                      <%= attachment_image_tag post_image, :image %>
                    <% end %>
                  </div>
                </div>
                <div class="block-content">
                 <%= attachment_image_tag post_image.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", class: "img-circle pull-left profile-thumb" %>
                  <%= link_to post_image_path(post_image.id) do %>
                     <i class="fa fa-map-marker"></i><%= post_image.shop_name %>
                  <% end %>
                  </h3>
                  <p><%= post_image.caption %></p>
                  <ul class="inline-meta">
                    <li>By
                      <%= post_image.user.name %>
                    </li>
                    <li>
                    <%= link_to "#{post_image.post_comments.count} コメント", post_image_path(post_image.id) %>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
             <%= paginate @post_images, class: "paginate" %>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

meshiterro2/app/views/post_images/new.html.erb
<section class="slice sct-color-1">
  <div class="container">
    <div class="row">
      <div class="col-md-12">

        <div class="row">
          <div class="col-md-6 col-md-offset-3 post_image_form">
            <div class="section-title-wrapper style-1 v1">
              <h3 class="section-title section-title-sm left">
                <span>画像投稿フォーム</span>
              </h3>
            </div>

            <!-- <form class="mt-20"> -->
<%= form_for(@post_image, url: post_images_path) do |f| %>
  <% if @post_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= @post_image.errors.count %>件のエラーが発生しました。</h2>
      <ul>
      <% @post_image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-sm-12">
      <%= f.attachment_field :image %>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-sm-6">
      <div class="form-group has-icon">
        <label class="control-label sr-only">ショップ名</label>
        <%= f.text_field :shop_name, class:"form-control", placeholder:"ショップ名" %>
        <span class="fa fa-building form-control-icon" aria-hidden="true"></span>
      </div>
    </div>
    <div class="col-sm-6">
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <%= f.text_area :caption, class:"form-control", rows:"3", placeholder:"コメントここに" %>
    </div>
  </div>
  <hr>
  <%= f.submit "送信", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
<% end %>
<!-- </form> -->
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

meshiterro2/app/views/post_images/show.html.erb
<section class="sct-color-1 slice">
  <div class="container">
    <div class="row">
      <div class="col-md-12 post_images_container">
        <div class="post-item">

          <div class="post-meta-top">
    　 <div class="post-image">
      　 <%= attachment_image_tag @post_image, :image %>
    　 </div>
  　 </div>
    <div class="post-content">
        <h2 class="post-title"><%= @post_image.shop_name %></h2>
        <ul class="meta-info-cells v4 float-wrapper">
          <li>
             <i class="fa fa-user"></i>By<a href="#">
             <%= @post_image.user.name %></a>
          </li>
          <li>
            <i class="fa fa-calendar"></i><%= @post_image.created_at.strftime('%Y/%m/%d') %>
          </li>
         <% if @post_image.favorited_by?(current_user) %>
<li>
    <%= link_to post_image_favorites_path(@post_image), method: :delete do %>
    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
    <%= @post_image.favorites.count %> いいね
    <% end %>
</li>
<% else %>
<li>
    <%= link_to post_image_favorites_path(@post_image), method: :post do %>
    <i class="fa fa-heart-o" aria-hidden="true"></i>
    <%= @post_image.favorites.count %> いいね
    <% end %>
</li>
<% end %>
          <li>
            <i class="fa fa-comment"></i>
            <a href="#comments"><%= @post_image.post_comments.count %></a>
          </li>
          <li>
      <% if @post_image.user == current_user %>
  <%= link_to "削除", post_image_path(@post_image), method: :delete %>
<% end %>
    </li>
        </ul>
        <div class="post-content-inner mt-20">
            <p><%= @post_image.caption %></p>
        </div>
    </div>
          <div class="comment-list bt style-2" id="comments">
            <div class="float-wrapper">
              <h2 class="comment-count"><%= @post_image.post_comments.count %>件コメント</h2>
            </div>
           <ol>
    <% @post_image.post_comments.each do |post_comment| %>
        <li class="comment">
            <div class="comment-body bb">
                <div class="comment-avatar">
                    <div class="avatar">
                        <%= attachment_image_tag post_comment.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
                    </div>
                </div>
                <div class="comment-text">
                    <div class="comment-author clearfix">
                        <a href="#" class="link-author"><%= post_comment.user.name %></a>
                        <span class="comment-meta">
                        <span class="comment-date"><%= post_comment.created_at.strftime('%Y/%m/%d') %></span>
                        </span>
                    </div>
                    <div class="comment-entry"><%= post_comment.comment %></div>
                </div>
            </div>
        </li>
    <% end %>
</ol>
          </div>
          <hr>

          <!-- Add comment section -->
          <div class="section-title-wrapper style-1 v1 mt-30" id="divAddComment">
            <h3 class="section-title left">
              <span>コメント</span>
            </h3>
          </div>
          <%= form_for [@post_image, @post_comment] do |f| %>
    <div class="row">
        <div class="col-sm-12">
            <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
        </div>
    </div>
    <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
<% end %>

        </div>
      </div>
    </div>
  </div>
</section>